apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sotto

resources:
  - namespace.yaml
  - mqtt-broker.yaml
  - ollama.yaml
  - transcription.yaml
  - agent-brain.yaml
  - tts.yaml
